const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'), W=canvas.width,H=canvas.height;
const ui={start:document.querySelector('#start'),over:document.querySelector('#gameover'),score:document.querySelector('#score'),time:document.querySelector('#time'),mult:document.querySelector('#mult'),best:document.querySelector('#best'),xp:document.querySelector('#xp'),coins:document.querySelector('#coins'),dash:document.querySelector('#dash'),signal:document.querySelector('#signal')};
const save=JSON.parse(localStorage.getItem('robot-arena-save')||'{"best":0,"xp":0,"coins":0}');
const art={};['arena','player_robot','laser','impact','movement-particles','danger-ring','explosion-1','explosion-2','explosion-3','explosion-area','missile','mine','damage-particles','dash-trail'].forEach(name=>{const image=new Image();image.src=`assets/${name}.${name==='arena'||name==='player_robot'?'webp':'png'}`;art[name]=image});
const spriteCache=new Map();
function cachedSprite(row,frame,filter){const key=`${row}:${frame}:${filter}`;if(spriteCache.has(key))return spriteCache.get(key);const tile=document.createElement('canvas');tile.width=422;tile.height=462;const tileCtx=tile.getContext('2d');tileCtx.imageSmoothingEnabled=false;tileCtx.filter=filter;tileCtx.drawImage(art.player_robot,frame*422,row,422,462,0,0,422,462);spriteCache.set(key,tile);return tile}
let avatar=0,running=false,last=0,started=0,score=0,shots=[],bots=[],particles=[],mines=[],keys={},player,spawnClock=0,mineClock=8,dashUntil=0,dashReady=0;
const skins=[['cyan','UNIDADE CIANO','NÚCLEO VETORIAL · PADRÃO','#31e7f7','none'],['pink','UNIDADE MAGENTA','NÚCLEO QUÂNTICO · RARO','#ff83c9','hue-rotate(110deg) saturate(1.35)'],['lime','UNIDADE LIMA','NÚCLEO BIÔNICO · ESTÁVEL','#8cec5b','hue-rotate(-105deg) saturate(1.45)'],['amber','UNIDADE ÂMBAR','NÚCLEO SOLAR · PROTÓTIPO','#ffc15a','hue-rotate(-135deg) saturate(1.55)']];
function sync(){['best','xp','coins'].forEach(k=>{document.querySelectorAll('#'+k+',#menu-'+k).forEach(e=>e.textContent=save[k])})}sync();
const preview=document.querySelector('#preview'),previewCtx=preview.getContext('2d');previewCtx.imageSmoothingEnabled=false;let previewRaf=0;
function previewLoop(){previewCtx.clearRect(0,0,160,185);if(art.player_robot.complete){let frame=Math.floor(performance.now()/110)%16;previewCtx.drawImage(cachedSprite(0,frame,skins[avatar][4]),15,4,130,170)}if(!ui.start.classList.contains('hidden'))previewRaf=requestAnimationFrame(previewLoop)}
function startPreview(){cancelAnimationFrame(previewRaf);previewLoop()}
function choose(n){avatar=(n+skins.length)%skins.length;let [,nm,core]=skins[avatar];document.querySelector('#unit').textContent=nm;document.querySelector('#core').textContent=core;startPreview()}document.querySelector('#previous').onclick=()=>choose(avatar-1);document.querySelector('#next').onclick=()=>choose(avatar+1);art.player_robot.addEventListener('load',startPreview);
function blend(image,x,y,w,h,rotation=0,alpha=1){if(!image.complete)return;ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.rotate(rotation);ctx.drawImage(image,-w/2,-h/2,w,h);ctx.restore()}
function robot(x,y,r,color,label,enemy=false,anim='idle',filter='none'){ctx.save();ctx.translate(x,y);ctx.rotate(r+Math.PI/2);if(art.player_robot.complete){const frame=Math.floor(performance.now()/95)%16,row=anim==='dash'?924:anim==='walk'?462:0;ctx.drawImage(cachedSprite(row,frame,filter),-37,-43,74,86)}else{ctx.shadowBlur=15;ctx.shadowColor=color;ctx.fillStyle='#52647a';ctx.strokeStyle='#9ab0bd';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(-16,-12,32,29,9);ctx.fill();ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(-12,-7,24,10,4);ctx.fill()}ctx.restore();ctx.font='bold 13px Rajdhani';ctx.textAlign='center';ctx.fillStyle=enemy?'#ffb0a0':color;ctx.fillText(label,x,y-42)}
function arena(){ctx.fillStyle='#091523';ctx.fillRect(0,0,W,H);if(art.arena.complete)ctx.drawImage(art.arena,0,0,W,H);else{ctx.strokeStyle='#172b3a';ctx.lineWidth=2;for(let x=75;x<W;x+=120){ctx.beginPath();ctx.moveTo(x,50);ctx.lineTo(x,H-50);ctx.stroke()}for(let y=50;y<H;y+=100){ctx.beginPath();ctx.moveTo(75,y);ctx.lineTo(W-75,y);ctx.stroke()}}ctx.fillStyle='#02081545';ctx.fillRect(0,0,W,H)}
function shoot(bot){let a=Math.atan2(player.y-bot.y,player.x-bot.x),speed=190+Math.min(150,score/150);shots.push({x:bot.x,y:bot.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:5,type:'orb'});}
function newBot(){let edge=Math.floor(Math.random()*4),x=edge<2?(edge?W-125:125):100+Math.random()*(W-200),y=edge>1?(edge===2?95:H-95):100+Math.random()*(H-200);let names=['Mika','Kora','Byte','Nex','Echo','Vex'];bots.push({x,y,color:'#ff5f5f',filter:'hue-rotate(180deg) saturate(1.65)',name:names[Math.floor(Math.random()*names.length)],cool:3.2+Math.random()*1.5,phase:Math.random()*6});}
function burst(x,y,color,n=14,kind='explosion-1'){particles.push({x,y,vx:0,vy:0,life:.55,color,kind,size:110});for(let i=0;i<n;i++){let a=Math.random()*7,v=50+Math.random()*220;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.3+Math.random()*.6,color,kind:'damage-particles',size:28})}}
function update(dt){let speed=(performance.now()<dashUntil?720:250),dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dy=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0);player.moving=!!(dx||dy);if(dx||dy){let l=Math.hypot(dx,dy);player.x+=dx/l*speed*dt;player.y+=dy/l*speed*dt;player.a=Math.atan2(dy,dx)}player.x=Math.max(110,Math.min(W-110,player.x));player.y=Math.max(90,Math.min(H-90,player.y));let elapsed=(performance.now()-started)/1000;spawnClock-=dt;mineClock-=dt;let botLimit=elapsed<35?2:elapsed<75?4:6;if(spawnClock<=0&&bots.length<botLimit){newBot();spawnClock=Math.max(1.45,4.8-score/560)}if(mineClock<=0&&mines.length<2&&elapsed>45){mines.push({x:180+Math.random()*(W-360),y:145+Math.random()*(H-290),life:8});mineClock=14+Math.random()*6}bots.forEach(b=>{b.cool-=dt;b.phase+=dt;if(b.cool<=0&&shots.length<16){shoot(b);b.cool=Math.max(1.2,3.1-score/950)+Math.random()*.8}});shots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(Math.hypot(s.x-player.x,s.y-player.y)<24&&performance.now()>dashUntil){burst(s.x,s.y,'#ff963f',10,'impact');end()}if(s.life<=0)burst(s.x,s.y,'#ffb63d',4,'impact')});shots=shots.filter(s=>s.life>0);mines.forEach(m=>{m.life-=dt;if(Math.hypot(m.x-player.x,m.y-player.y)<42&&performance.now()>dashUntil){burst(m.x,m.y,'#ff963f',20,'explosion-3');end()}});mines=mines.filter(m=>m.life>0);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});particles=particles.filter(p=>p.life>0).slice(-90);score+=dt*10;let t=(performance.now()-started)/1000,mult=1+Math.floor(t/25)*.1;ui.score.textContent=String(Math.floor(score*mult)).padStart(6,'0');ui.time.textContent=`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;ui.mult.textContent='x'+mult.toFixed(1);let pct=Math.max(0,Math.min(1,(performance.now()-dashReady)/1250));ui.dash.querySelector('em').style.width=(pct*100)+'%';ui.dash.querySelector('span').textContent=pct>=1?'DASH PRONTO':'RECARREGANDO';}
function draw(){arena();bots.forEach(b=>{let a=Math.atan2(player.y-b.y,player.x-b.x);if(b.cool<.32)blend(art['danger-ring'],b.x,b.y,73,73,0,.7);robot(b.x,b.y,a,b.color,b.name,true,'walk',b.filter)});mines.forEach(m=>blend(art.mine,m.x,m.y,48,48,0,.85));shots.forEach(s=>{ctx.save();ctx.shadowBlur=18;ctx.shadowColor='#ff263b';ctx.fillStyle='#ff3146';ctx.beginPath();ctx.arc(s.x,s.y,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffe0d3';ctx.globalAlpha=.8;ctx.beginPath();ctx.arc(s.x-2,s.y-2,3,0,Math.PI*2);ctx.fill();ctx.restore()});particles.forEach(p=>blend(art[p.kind],p.x,p.y,p.size,p.size,0,Math.max(0,p.life*2)));if(performance.now()<dashUntil)blend(art['dash-trail'],player.x-32*Math.cos(player.a),player.y-32*Math.sin(player.a),105,48,player.a,0.9);robot(player.x,player.y,player.a,skins[avatar][3],player.name,false,performance.now()<dashUntil?'dash':player.moving?'walk':'idle',skins[avatar][4]);}
function frame(now){if(!running)return;let dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(frame)}
function start(){player={x:W/2,y:H/2,a:-Math.PI/2,name:document.querySelector('#name').value.trim()||'Piloto-01'};score=0;shots=[];bots=[];particles=[];mines=[];spawnClock=2.5;mineClock=50;started=performance.now();dashReady=0;running=true;ui.start.classList.add('hidden');ui.over.classList.add('hidden');ui.signal.style.opacity=1;setTimeout(()=>ui.signal.style.opacity=0,1800);last=started;requestAnimationFrame(frame)}
function end(){if(!running)return;running=false;burst(player.x,player.y,skins[avatar][3],40,'explosion-2');draw();let points=Math.floor(score*(1+Math.floor((performance.now()-started)/25000)*.1));save.best=Math.max(save.best,points);save.xp+=Math.floor(points/12);save.coins+=Math.floor(points/35);localStorage.setItem('robot-arena-save',JSON.stringify(save));sync();document.querySelector('#final-score').textContent=points;document.querySelector('#final-time').textContent=ui.time.textContent;document.querySelector('#final-xp').textContent='+'+Math.floor(points/12);ui.over.classList.remove('hidden')}
document.querySelector('#start-form').addEventListener('submit',e=>{e.preventDefault();start()});document.querySelector('#retry').onclick=()=>{ui.start.classList.remove('hidden');ui.over.classList.add('hidden');draw();startPreview()};addEventListener('keydown',e=>{keys[e.key]=true;if(e.key==='Shift'&&running&&performance.now()>=dashReady){dashUntil=performance.now()+170;dashReady=performance.now()+1250;burst(player.x,player.y,skins[avatar][3],12)}if(e.key==='Enter'&&!running&&ui.start&&!ui.start.classList.contains('hidden'))start()});addEventListener('keyup',e=>keys[e.key]=false);draw();
